In [8]:
import numpy as np

In [9]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1.shape, a1.ndim, a1.dtype)

[1 2 3]
(3,) 1 int64


Shape: print(a1.shape). Output: (3,)
Shape tells you how many elements exist along each axis.
It is a tuple. Each number answers: “how many things live in this direction?”
(3,) - “There is 1 axis, and it has 3 elements.”
Shape is metadata.
Data lives in memory as a flat block.


ndim:   ndim == len(shape)

ndim: print(a1.ndim) output: 1
ndim: how many axes exist
ndim is just the length of shape. Here a1 has 1 axis - 1 ndim

2D: rows and columns appear: 
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)
print(b.ndim)

Output:
(2, 3)
2

Interpretation:

Axis 0 → 2 rows
Axis 1 → 3 columns

So the rule is:
Each number in shape is one dimension (axis).
Two numbers → 2D array.

3D: stacks of tables
c = np.zeros((4, 2, 3))
print(c.shape)
print(c.ndim)

Output:

(4, 2, 3)
3

Interpretation:
4 “layers”
each layer has 2 rows
each row has 3 columns

This is common in:
images (height × width × channels)
time-series batches
ML tensors


shape = how many elements along each axis
ndim = number of axes
ndim == len(shape) always
Geometry ≠ data

In [10]:
a2= np.zeros((3, 4))
print(a2)
print(a2.shape, a2.ndim, a2.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4) 2 float64


In [11]:
a3 = np.ones((2, 3))
print(a3)
print(a3.shape, a3.ndim, a3.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3) 2 float64


In [12]:
a4 = np.arange(0, 10, 2)
print(a4)
print(a4.shape, a4.ndim, a4.dtype)

[0 2 4 6 8]
(5,) 1 int64


In [13]:
lst = [1, 2, 3]
arr = np.array(lst)

print(lst * 2)
print(arr * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [14]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3.0])

print(a.dtype)
print(b.dtype)

int64
float64


1. Arrays are fixed-type
2. Shape describes geometry
3. Arrays do math, lists store objects