# **NUMPY**:

1. Numpy is short for Numerical Python, which is a python library. It is used for working with arrays.

2. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

## **Python Lists vs Numpy Arrays**:

**They differ in what they store, how they are stored in memory, and how operations are executed.**

### **1. What they store**:

#### **Python list**:

- Stores references to Python objects
- Each element can be a different type
- Every element is a full Python object

**Example:**

[1, 2.5, "a", True] # A list with elements of different datatypes
This flexibility is powerful, but expensive.

#### **NumPy array**:

- Stores raw values, not Python objects
- All elements have the same data type (dtype)
- Values are stored directly in memory

**Example:**
np.array([1, 2, 3])   # all int

This restriction is what enables speed.

### **2. Memory layout (this is the core reason for speed)**

#### **Python list memory**

- Elements live in different locations in memory
- The list holds pointers to those locations
- CPU must jump around in memory to access elements

**Result:**

- Poor cache usage
- Slower numerical operations

#### **NumPy array memory**

- Elements are stored in one contiguous block of memory
- No pointers per element
- CPU can read data sequentially

**Result:**

- Excellent cache locality
- Predictable memory access
- Much faster numerical computation

### **3. Fixed type vs dynamic type**

#### **Python list:**

- Each element checks its type at runtime
- Arithmetic requires repeated type checks
- Operations happen one element at a time

#### **NumPy array**

- dtype is known in advance
- No per-element type checking
- Operations are applied to the whole array at once

**This allows NumPy to use compiled C loops instead of Python loops.**

### **4. How operations are executed:**

**Python list**

lst = [1, 2, 3]
lst * 2

Result:

[1, 2, 3, 1, 2, 3]
This is list concatenation, not math.

To do math, you need a loop:
[x * 2 for x in lst]

That loop runs in Python, which is slow.


**NumPy array:**

arr = np.array([1, 2, 3])
arr * 2

Result:
[2 4 6]

This operation:  

- runs in compiled C code
- uses vectorized instructions
- avoids Python loops entirely

### **5. Vectorization**

NumPy performs vectorized operations:
- one instruction applies to many values
- loops happen in optimized C, not Python
- often uses SIMD (Single Instruction, Multiple Data)

**This is why:**
arr + arr is fast, while Python needs a loop.

### **6. Views, copies, and memory efficiency**: 

Python list :
- Slicing always creates a new list
- Memory is always copied

NumPy array :
- Slicing usually creates a view
- Multiple arrays can share the same memory
- No copy unless explicitly requested

This enables:
- low memory usage
- fast reshaping
- efficient pipelines

### **7. When lists are better than NumPy**

Lists are better when:
- Data is small
- Types are mixed
- Need frequent appends/removals
- Not doing numerical computation

NumPy is better when:
- Data is numerical
- Size is large
- Performance matters
- Memory layout matters

### **One-line summary**:

Python lists are flexible containers of objects;
NumPy arrays are fixed-type, contiguous blocks of numerical data optimized for fast computation.

### **Importing numpy**:

In [1]:
import numpy as np

### **Checking NumPy Version**:

In [2]:
print(np.__version__)

1.26.4


## **NumPy Creating Arrays**:
NumPy provides multiple creation methods because different problems need different starting states.

#### **1.From Python sequences (np.array)**: 
Create arrays from lists or tuples.

In [3]:
np.array([1, 2, 3])
np.array([[1, 2, 3], [4, 5, 6]])
np.array([1, 2, 3.5])   # dtype becomes float

array([1. , 2. , 3.5])

Notes:
- Nested lists determine dimensions
- NumPy infers dtype
- Mixed types are upcast if possible

Use this when:
- converting existing Python data
- small or manually specified arrays

#### **2.Arrays filled with zeros (np.zeros)**:

In [4]:
print(np.zeros(5)) # 1 Dimension  of default dtype float
print("\n",np.zeros((2, 3))) # 2 Dimension (2 Rows and 3 columns) of default dtype float
print("\n",np.zeros((2, 3), dtype=int))  # 2 Dimension (2 Rows and 3 columns) of dtype int


[0. 0. 0. 0. 0.]

 [[0. 0. 0.]
 [0. 0. 0.]]

 [[0 0 0]
 [0 0 0]]


Creates arrays filled with 0 of dafault dtype float of specified shape.

**Why this exists:**
- fast memory allocation
- common initialization pattern in numerical code
- can specify other dtype when default dtype of float isnt required. eg print("\n",np.zeros((2, 3), dtype=int))

#### **3.Arrays filled with ones (np.ones)**:

Same idea as zeros, but filled with 1.
Used often for:
- initialization
- testing
- broadcasting examples

In [5]:
print(np.ones(4))  # 1D default dtype is float
print("\n",np.ones((3, 2))) # 2D default dtype is float
print("\n", np.ones((3,2),dtype = 'int'))   # 2D of dtype int

[1. 1. 1. 1.]

 [[1. 1.]
 [1. 1.]
 [1. 1.]]

 [[1 1]
 [1 1]
 [1 1]]


#### **4.Uninitialized arrays (np.empty)**:

**Important:**
- values are whatever already exists in memory
- neither guranteed zero's nor one's. Contains garbage values
- extremely fast

**Use only when:**
- you will immediately overwrite all values

In [ ]:
print("Empty : ",np.empty(5)) # 1D of default dtype float. neither guranteed zero's nor one's. Contains garbage values
print("\n",np.empty((2, 3))) # 2D of default dtype float. neither guranteed zero's nor one's. Contains garbage values
print("\n",np.empty((2,3),dtype = 'int')) # 2D of dtype int. neither guranteed zero's nor one's. Contains garbage values

Empty :  [0. 0. 0. 0. 0.]

 [[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]

 [[1 1 1]
 [1 1 1]]


#### **5.Evenly spaced values (np.arange)**:

Similar to Python range, but returns an array.
**Characteristics:**
- fast
- half-open interval [start, stop)
- step size is fixed

**Prefer for:**
- index-based sequences
- integer ranges

In [7]:
print(np.arange(5)) # Starts from 0 by default
print("\n",np.arange(1, 10, 2)) # Start value 1, stop value :10(not inclusive), step value : 2 (every 2nd element))


[0 1 2 3 4]

 [1 3 5 7 9]


#### **6.Linearly spaced values (np.linspace)**:

Creates exactly N values between start and end (inclusive).

**Why this exists:**
- floating-point precision
- scientific computations
- plotting

**Difference from arange:**
- linspace controls number of points
- arange controls step size



In [8]:
np.linspace(0, 1, 5)  # start value 0, stop value 1 (inclusive) split value 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### **7.Identity and diagonal matrices :**

**Used in:**
- linear algebra
- matrix initialization
- ML algorithms

In [9]:
# Identity matrix
print("Identity Matrix :np.eye(3) : \n",np.eye(3)) # 2D Default dtype is float

# Diagonal matrix
print("\nDiagonal Matrix np.diag([1,2,3]) : \n",np.diag([1, 2, 3]))    # 2D dtype int

Identity Matrix :np.eye(3) : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Matrix np.diag([1,2,3]) : 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


#### **8.Random arrays:**

Used for:
- simulations
- testing
- ML initialization

In [10]:
print(np.random.rand(2, 3)) 
print("\n",np.random.randn(2, 3))
print("\n",np.random.randint(0, 10, size=(3, 4)))


[[0.11055806 0.36950257 0.77735335]
 [0.85450868 0.27735963 0.61709851]]

 [[-1.56002394 -0.61444353  0.35119218]
 [-0.3322434  -0.8055822  -0.72590824]]

 [[7 5 1 9]
 [9 0 9 4]
 [2 7 0 2]]


#### **9.Creating arrays with a specified dtype:**

Why this matters:
- memory usage
- numerical precision
- performance

In [11]:
print(np.array([1, 2, 3], dtype=float))
print("\n",np.zeros((2, 2), dtype=np.int32))

[1. 2. 3.]

 [[0 0]
 [0 0]]


## **What is an ndarray?**
A NumPy ndarray (N-dimensional array) is:
- a collection of same-type values
- stored in one contiguous block of memory
- interpreted using shape (geometry) and dtype (data type)

**Data and structure are separate:**

data → raw numbers in memory
metadata → how NumPy views that memory

**Key attributes:**
- ndim → number of dimensions (axes)
- shape → size along each axis
- dtype → type of each element

In [12]:
a1 = np.array([1, 2, 3])
print("The array a1 is : \n",a1)
print("\na1.shape is : ",a1.shape,"\na1.ndim is : ",a1.ndim,"\na1.dtype is : ",a1.dtype)

The array a1 is : 
 [1 2 3]

a1.shape is :  (3,) 
a1.ndim is :  1 
a1.dtype is :  int64


#### **Shape:** 
print(a1.shape). Output: (3,)

- Shape tells you how many elements exist along each axis.
- It is a tuple. Each number answers: “how many things live in this direction?”
- (3,) - “There is 1 axis, and it has 3 elements.”
- Shape is metadata.
- Data lives in memory as a flat block.

#### **ndim**
**ndim:   ndim == len(shape)**

ndim: print(a1.ndim) output: 1
- ndim: how many axes exist
- ndim is just the length of shape. Here a1 has 1 axis - 1 ndim

**2D:** rows and columns appear: 
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)
print(b.ndim)

Output:
(2, 3)
2

**Interpretation:**

Axis 0 → 2 rows
Axis 1 → 3 columns

**So the rule is:**
Each number in shape is one dimension (axis).
Two numbers → 2D array.

**3D:** stacks of tables
c = np.zeros((4, 2, 3))
print(c.shape)
print(c.ndim)

Output:

(4, 2, 3)
3

**Interpretation:**
4 “layers”
each layer has 2 rows
each row has 3 columns

This is common in:
images (height × width × channels)
time-series batches
ML tensors


shape = how many elements along each axis
ndim = number of axes
ndim == len(shape) always
Geometry ≠ data

In [13]:
a2= np.zeros((3, 4))
print(a2)
print(a2.shape, a2.ndim, a2.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4) 2 float64


In [14]:
a3 = np.ones((2, 3))
print(a3)
print(a3.shape, a3.ndim, a3.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3) 2 float64


In [15]:
a4 = np.arange(0, 10, 2)
print(a4)
print(a4.shape, a4.ndim, a4.dtype)

[0 2 4 6 8]
(5,) 1 int64


In [16]:
lst = [1, 2, 3]
arr = np.array(lst)

print(lst * 2)
print(arr * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [17]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3.0])

print(a.dtype)
print(b.dtype)

int64
float64


1. Arrays are fixed-type
2. Shape describes geometry
3. Arrays do math, lists store objects
4. NumPy arrays store data and metadata separately
5. Data lives as a flat block of memory
6. shape and ndim only describe how to interpret that data
7. Changing shape does not change data
8. Math works on arrays, not element-by-element Python objects