In [1]:
import numpy as np

In [2]:
x = np.arange(6)
print("x : ",x)
print("x shape : ",x.shape)
print("ndim of x : ",x.ndim)


x :  [0 1 2 3 4 5]
x shape :  (6,)
ndim of x :  1


In [3]:
y = x.reshape(2,3)
print("y : ",y)
print("y shape : ",y.shape)
print("ndim of y : ",y.ndim)

y :  [[0 1 2]
 [3 4 5]]
y shape :  (2, 3)
ndim of y :  2


In [4]:
y[0,0] = 999
print("After changing y[0,0] = 999 : \n",y)
print("Printing x after changing y[0,0] = 999 : \n", x)

After changing y[0,0] = 999 : 
 [[999   1   2]
 [  3   4   5]]
Printing x after changing y[0,0] = 999 : 
 [999   1   2   3   4   5]


In [5]:
print("x.base : ", x.base)
print("y.base is x : ", y.base is x)

x.base :  None
y.base is x :  True


In [6]:
z = x.reshape(2, 3).copy()
z[0, 0] = -1
print("After changing z[0,0] = -1")
print("z :\n", z)
print("y :\n", x)
print("x :\n", x)

After changing z[0,0] = -1
z :
 [[-1  1  2]
 [ 3  4  5]]
y :
 [999   1   2   3   4   5]
x :
 [999   1   2   3   4   5]


View = shares memory (changing one changes the other)

Copy = owns memory (changes don’t leak)

reshape often returns a view; .copy() always makes a copy