In [1]:
import numpy as np

NumPy is imported as np.
This notebook focuses on advanced indexing (filtering/selecting/assigning) and the most important rule:

Basic slicing usually returns a view
Boolean & fancy indexing usually return a copy

In [2]:
# Array creation
x = np.arange(12).reshape(3, 4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

We use the same 2D array for all examples:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


shape = (3, 4) → 3 rows, 4 columns

x[row, col] accesses one element

In [ ]:
# Boolean indexing (filtering)

mask = x > 5
mask


A boolean mask is an array of True/False with the same shape as x.

True means “select this”

False means “ignore this”

Here, mask marks all values > 5.

In [ ]:
x[mask]


x[mask] returns a 1D array of selected elements.

Important:

Output becomes 1D because we are “extracting values” not “keeping the grid”.

Boolean indexing returns a copy (in most cases).

In [ ]:
x[x > 5]


This is the common shortcut:
Instead of creating mask separately, you can directly write the condition.

In [ ]:
#Boolean indexing assignment
x = np.arange(12).reshape(3, 4)

x[x > 5] = 100
x


This is a powerful pattern:

x > 5 creates a mask

x[mask] = 100 updates only those positions

This modifies the original array x directly.

In [ ]:
# np.where (select values conditionally)

x = np.arange(12).reshape(3, 4)

y = np.where(x > 5, 1, 0)
y


np.where(condition, value_if_true, value_if_false) creates a new array.

Here:

if x > 5 → put 1

else → put 0

This is useful for making “label” arrays.

In [ ]:
idx = np.where(x > 5)
idx

When np.where is used with only a condition:

np.where(condition) returns indices of True values.

For 2D arrays, it returns:

row indices array

column indices array

You can use it to locate positions.

In [ ]:
# Fancy indexing (indexing with lists/arrays)

x = np.arange(12).reshape(3, 4)

rows = [0, 2]
x[rows]


When you index with a list/array of indices, it is called fancy indexing.

x[[0, 2]] selects:

row 0

row 2

⚠️ Fancy indexing returns a copy, not a view.

In [ ]:
cols = [1, 3]
x[:, cols]


x[:, [1, 3]] selects columns 1 and 3 from all rows.

Again: fancy indexing usually returns a copy.

In [ ]:
# Important pitfall: selecting rows and columns together

x = np.arange(12).reshape(3, 4)

x[[0, 2], [1, 3]]


This surprises many learners.

This does pair selection, not a submatrix:

It selects:

(row 0, col 1)

(row 2, col 3)

So the result is 1D, like:

[ x[0,1], x[2,3] ]
If you want a submatrix, use np.ix_.


In [ ]:
# Correct way: np.ix_ for row/column submatrix
x = np.arange(12).reshape(3, 4)

rows = [0, 2]
cols = [1, 3]

x[np.ix_(rows, cols)]


np.ix_(rows, cols) creates an index grid that selects the full rectangle.

This returns the true submatrix:

Rows: 0 and 2
Cols: 1 and 3

Result shape becomes (2, 2).

In [ ]:
# View vs copy test (must know)

x = np.arange(12).reshape(3, 4)

a = x[:, 1:3]       # basic slicing
b = x[:, [1, 2]]    # fancy indexing

a[0, 0] = 999

x, a, b


This shows the critical difference:

a = x[:, 1:3] → basic slicing → usually a view

b = x[:, [1, 2]] → fancy indexing → usually a copy

When we modify a, x changes too.
But b is independent.



Key takeaways

Boolean masks: x[x > 5] filter values (usually copy)

Mask assignment: x[x > 5] = 100 edits selected positions

np.where(cond, a, b) builds new arrays using conditions

Fancy indexing uses lists/arrays: x[[0, 2]], x[:, [1, 3]] (usually copy)

x[[rows], [cols]] selects pairs (not submatrix)

Use np.ix_ to get a proper submatrix

View vs copy: slicing → view, boolean/fancy → copy (most of the time)